name: Deploy Infrastructure

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Deploy Services
        run: |
          docker compose -f infrastructure/docker-compose.yml up -d
